pipeline {
    agent any

    environment {

    DOCKERHUB_CREDENTIALS = credentials('akhil')
     registry = "yellaiahdocker/lmss-k8s"
        registryCredential = 'akhil'
        dockerImage = ''
    }

    stages {

        stage('Building the docker image') {
            steps {
                sh 'cd webapp && docker build -t yellaiahdocker/lmss-k8s .'
            }
        }
        stage('Logging into dockerhub account') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('pushing the docker image into dockerhub') {
            steps {
                  sh 'docker push yellaiahdocker/lmss-k8s'
            }
        }
        stage('Remove old docker images') {
             steps {
                 sh 'docker rmi -f yellaiahdocker/lmss-k8s'

            }
        }
         stage('Running on kubernetes') {
            steps {
                echo 'Deploying....'
                 
                sh "cd webapp && kubectl apply -f frontend-deployment.yaml"
                sh "cd webapp && kubectl apply -f frontend-load-balancer-service.yaml"
                sh "kubectl rollout restart deployment frontend-deployment"
            }
        }
    }
}
