pipeline {
    agent{
       label 'k8s'

     }

    environment {

    DOCKERHUB_CREDENTIALS = credentials('docker-hub')
     registry = "yellaiahdocker/new-webapp"
        registryCredential = 'docker-hub'
        dockerImage = ''
    }

    stages {

        stage('Building the docker image') {
            steps {
                sh 'cd webapp && docker build -t yellaiahdocker/new-webapp .'
            }
        }
        stage('Logging into dockerhub account') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('pushing the docker image into dockerhub') {
            steps {
                  sh 'docker push yellaiahdocker/new-webapp'
            }
        }
        stage('Remove old docker images') {
             steps {
                 sh 'docker rmi -f yellaiahdocker/new-webapp'

            }
        }
         stage('Running on kubernetes') {
            steps {
                echo 'Deploying....'
               
                 
                sh "cd webapp && kubectl apply  -f  frontend-deployment.yaml"
                sh "cd webapp && kubectl apply  -f  frontend-load-balancer-service.yaml"
            }
        }
    }
}
