pipeline {
    agent{
       label 'k8s'

     }

    environment {

    DOCKERHUB_CREDENTIALS = credentials('docker-hub')
     registry = "yellaiahdocker/new-api"
        registryCredential = 'docker-hub'
        dockerImage = ''
    }

    stages {

        stage('Building the docker image') {
            steps {
                sh 'cd api && docker build -t yellaiahdocker/new-api .'
            }
        }
        stage('Logging into dockerhub account') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('pushing the docker image into dockerhub') {
            steps {
                  sh 'docker push yellaiahdocker/new-api'
            }
        }
        stage('Remove old docker images') {
             steps {
                 sh 'docker rmi -f yellaiahdocker/new-api'

            }
        }
         stage('Running on kubernetes') {
            steps {
                echo 'Deploying....'
                sh "cd api && kubectl create -f postgres-deployment.yaml"
                 sh "cd api && kubectl create -f postgres-cluster-ip-service.yaml"
                sh "cd api && kubectl create -f api-deployment.yaml"
                sh "cd api && kubectl create -f api-load-balancer-service.yaml"
                sh "kubectl rollout restart deployment api-deployment"
            }
        }
    }
}
